<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OmniCore.Services.Auth.Application\OmniCore.Services.Auth.Application.csproj" />
    <ProjectReference Include="..\..\OmniCore.Shared\OmniCore.Shared.Infrastructure\OmniCore.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
