<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.S3" Version="4.0.18.5" />
		<PackageReference Include="EFCore.BulkExtensions" Version="9.0.2" />
		<PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
		<PackageReference Include="MassTransit" Version="8.5.7" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.7" />
		<PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.13" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="Quartz" Version="3.15.0" />
		<PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.15.0" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.0" />
		<PackageReference Include="Scrutor" Version="7.0.0" />

		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.12.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.12.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.12.0" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
		<PackageReference Include="UAParser" Version="3.1.47" />

	</ItemGroup>

	<ItemGroup>
    	<ProjectReference Include="..\OmniCore.Shared.Application\OmniCore.Shared.Application.csproj" />
    	<ProjectReference Include="..\OmniCore.Shared.Domain\OmniCore.Shared.Domain.csproj" />
	</ItemGroup>


</Project>
